name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 소스를 체크아웃
    - name: Check out the repository
      uses: actions/checkout@v4

    # 2. JDK 17 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    # 3. 의존성 다운로드 및 빌드 (Gradle 빌드 사용)
    - name: Build with Gradle
      run: ./gradlew build

    # 4. Docker 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # 5. Docker 이미지 빌드
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/coverranking:${{ github.sha }}

    # 6. Docker Hub에 이미지 푸시
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/coverranking:${{ github.sha }}

    # 7. Docker 컨테이너 실행 (테스트용)
    - name: Run Docker container
      run: docker run -d -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/coverranking:${{ github.sha }}
